name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Create site files
        run: |
          mkdir -p ./_site
          
          # Create index.html
          cat > ./_site/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>NeuralEcho</title>
          </head>
          <body>
              <h1>Welcome to NeuralEcho</h1>
              <p>An interactive narrative experience exploring the boundaries between neuroscience, artificial intelligence, and human consciousness.</p>
          </body>
          </html>
          EOL
          
          # Create 404.html
          cat > ./_site/404.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Page Not Found - NeuralEcho</title>
          </head>
          <body>
              <h1>404 - Page Not Found</h1>
              <p>The page you are looking for does not exist.</p>
              <a href="/">Return to Home</a>
          </body>
          </html>
          EOL
          
      - name: List _site directory
        run: ls -la ./_site
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 